services:
  database:
    image: postgres
    container_name: 'techno-watcher-database'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techno_watcher_test
